# Generated by Django 4.2.6 on 2023-10-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_remove_transactions_receiverid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateOpened", models.DateField(auto_created=True)),
                (
                    "accountNumber",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "accountType",
                    models.CharField(
                        choices=[("Chequing", "Chequing"), ("Savings", "Savings")],
                        default="Chequing",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("interestRate", models.FloatField()),
                ("dateClosed", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "receiverId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.accounts",
                    ),
                ),
                (
                    "senderId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.accounts",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="accounts",
            name="transactions",
            field=models.ManyToManyField(
                related_name="transaction",
                through="accounts.Transactions",
                to="accounts.accounts",
            ),
        ),
        migrations.AddField(
            model_name="accounts",
            name="userId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.users"
            ),
        ),
    ]
